const LM = [
  {
    drugId: "l1",
    catId: [],
    drugName: "KlondrugIdin",
    styrka: "15 µg/ml",
    recept: "1 ml catapressan 150 µg/ml + 9 ml NaCl",
    dosimG: "",
    dosIµG: 1,
    obs: "barn > 1 år",
  },
  {
    drugId: "l2",
    catId: [],
    drugName: "Ondansetron",
    styrka: "2 mg/ml",
    recept: "",
    dosimG: 0.1,
    dosIµG: "",
    obs: "maximalt 2 ml",
  },
  {
    drugId: "l3",
    catId: [],
    drugName: "Betapred",
    styrka: "4 mg/ml",
    recept: "",
    dosimG: 0.2,
    dosIµG: "",
    obs: "maximalt 1 ml",
  },
  {
    drugId: "l4",
    catId: [],
    drugName: "Phenergan",
    styrka: "25 mg/ml",
    recept: "",
    dosimG: 0.5,
    dosIµG: "",
    obs: "maximalt 0,5 ml",
  },

  {
    drugId: "l6",
    catId: [],
    drugName: "Atropin",
    styrka: "0.5 mg/ml",
    recept: "",
    dosiMg: "",
    dosIµG: 10,
    obs: "maximalt 1 ml",
  },
];

export default LM;
