export const DRUGS = [
  {
    drugId: new Date().getTime(),
    catId: ["c7"],
    drugName: "Klonidin",
    styrka: "15 µg/ml",
    recept: "1 ml catapressan 150 µg/ml + 9 ml NaCl",
    dosimG: "",
    dosIµG: 1,
    obs: "barn > 1 år",
  },
  {
    drugId: new Date().getTime(),
    catId: ["c8"],
    drugName: "Ondansetron",
    styrka: "2 mg/ml",
    recept: "",
    dosimG: 0.1,
    dosIµG: "",
    obs: "maximalt 2 ml",
  },
  {
    drugId: new Date().getTime(),
    catId: ["c8"],
    drugName: "Betapred",
    styrka: "4 mg/ml",
    dosimG: 0.2,
    dosIµG: "",
    obs: "maximalt 1 ml",
  },
  {
    drugId: new Date().getTime(),
    catId: ["c8"],
    drugName: "Phenergan",
    styrka: "25 mg/ml",
    dosimG: 0.5,
    dosIµG: "",
    obs: "maximalt 0,5 ml",
  },
  {
    drugId: new Date().getTime(),
    catId: ["c2", "c4"],
    drugName: "Dexdor",
    styrka: "100 µg/ml",
    dosIµG: 1,
    dosIµG_2: 2,
    obs: "Nasalt",
  },
  {
    drugId: new Date().getTime(),
    catId: ["c2", "c5"],
    drugName: "Atropin",
    styrka: "0.5 mg/ml",
    dosIµG: 10,
    obs: "maximalt 1 ml",
  },

  {
    drugId: new Date().getTime(),
    catId: ["c1"],
    drugName: "Midazolam",
    styrka: "1 mg/ml",
    recept: "",
    dosimG: 0.1,
    dosIµG: "",
    obs: " ",
  },
  {
    drugId: new Date().getTime(),
    catId: ["c1"],
    drugName: "Midazolam",
    styrka: "5 mg/ml",
    recept: "",
    dosimG: 0.1,
    dosIµG: "",
    obs: " ",
  },
  {
    drugId: new Date().getTime(),
    catId: ["c5"],
    drugName: "Robinul",
    styrka: "0.2 mg/ml",
    recept: "",
    dosimG: "",
    dosIµG: 10,
    obs: " ",
  },
  {
    drugId: new Date().getTime(),
    catId: ["c2"],
    drugName: "Ketalar",
    styrka: "10 mg/ml",
    recept: "",
    dosimG: 2,
    dosIµG: "",
    obs: " ",
  },
  {
    drugId: new Date().getTime(),
    catId: ["c2"],
    drugName: "Ketanest",
    styrka: "5 mg/ml",
    recept: "",
    dosimG: 0.5,
    dosimG_2: 1,
    dosIµG: "",
    obs: " ",
  },
  {
    drugId: new Date().getTime(),
    catId: ["c2"],
    drugName: "Ketanest",
    styrka: "25 mg/ml",
    recept: "",
    dosimG: 0.5,
    dosimG_2: 1,
    dosIµG: "",
    obs: " ",
  },
  {
    drugId: new Date().getTime(),
    catId: ["c2"],
    drugName: "Ketalar",
    styrka: "50 mg/ml",
    recept: "",
    dosimG: 2,
    dosIµG: "",
    obs: " ",
  },
  {
    drugId: new Date().getTime(),
    catId: ["c2"],
    drugName: "Penthotal",
    styrka: "25 mg/ml",
    recept: "1 st Torrrampull i 20 ml Sterilt vatten",
    dosimG: 5,
    dosIµG: "",
  },
  {
    drugId: new Date().getTime(),
    catId: ["c2"],
    drugName: "Propofol",
    styrka: "10 mg/ml",
    recept: "",
    dosiMg: 2,
    dosiMg_2: 3,
    dosIµG: "",
    obs: " ",
  },
  {
    drugId: new Date().getTime(),
    catId: ["c3"],
    drugName: "Alfentanil",
    styrka: "0.5 mg/ml",
    recept: "",
    dosimG: "",
    dosIµG: 5,
    dosIµG_2: 10,
    dosIµG_3: 20,
    obs: " ",
  },
];
