export const DRUGS = [
  {
    drugId: "l1",
    catId: ["c2", "c5"],
    drugName: "Klonidin",
    styrka: "15 µg/ml",
    recept: "1 ml catapressan 150 µg/ml + 9 ml NaCl",
    dosimG: "",
    dosIµG: 1,
    obs: "barn > 1 år",
  },
  {
    drugId: "l2",
    catId: ["c1"],
    drugName: "Ondansetron",
    styrka: "2 mg/ml",
    recept: "",
    dosimG: 0.1,
    dosIµG: "",
    obs: "maximalt 2 ml",
  },
  {
    drugId: "l3",
    catId: ["c1"],
    drugName: "Betapred",
    styrka: "4 mg/ml",
    recept: "",
    dosimG: 0.2,
    dosIµG: "",
    obs: "maximalt 1 ml",
  },
  {
    drugId: "l4",
    catId: ["c1"],
    drugName: "Phenergan",
    styrka: "25 mg/ml",
    recept: "",
    dosimG: 0.5,
    dosIµG: "",
    obs: "maximalt 0,5 ml",
  },
  {
    drugId: "l5",
    catId: ["c2", "c4"],
    drugName: "Dexdor",
    styrka: "100 µg/ml",
    recept: "",
    dosimG: 1,
    dosimG_2: 2,
    dosIµG: "",
    obs: "Nasalt",
  },

  {
    drugId: "l6",
    catId: ["c3", "c7"],
    drugName: "Atropin",
    styrka: "0.5 mg/ml",
    recept: "",
    dosiMg: "",
    dosIµG: 10,
    obs: "maximalt 1 ml",
  },

  {
    drugId: "l7",
    catId: ["c2"],
    drugName: "Midazolam",
    styrka: "1 mg/ml",
    recept: "",
    dosiMg: 0.1,
    dosIµG: "",
    obs: " ",
  },
  {
    drugId: "l8",
    catId: ["c2"],
    drugName: "Midazolam",
    styrka: "5 mg/ml",
    recept: "",
    dosiMg: 0.1,
    dosIµG: "",
    obs: " ",
  },
  {
    drugId: "l9",
    catId: ["c3", "c4", "c7"],
    drugName: "Robinul",
    styrka: "0.2 mg/ml",
    recept: "",
    dosiMg: "",
    dosIµG: 5,
    obs: " ",
  },
  {
    drugId: "l10",
    catId: ["c5", "c6"],
    drugName: "Ketalar",
    styrka: "10 mg/ml",
    recept: "",
    dosiMg: 2,
    dosIµG: "",
    obs: " ",
  },
  {
    drugId: "l11",
    catId: ["c5", "c6"],
    drugName: "Ketanest",
    styrka: "5 mg/ml",
    recept: "",
    dosiMg: 0.5,
    dosiMg_2: 1,
    dosIµG: "",
    obs: " ",
  },
  {
    drugId: "l12",
    catId: ["c5", "c6"],
    drugName: "Ketanest",
    styrka: "25 mg/ml",
    recept: "",
    dosiMg: 0.5,
    dosiMg_2: 1,
    dosIµG: "",
    obs: " ",
  },
  {
    drugId: "l13",
    catId: ["c5", "c6"],
    drugName: "Ketalar",
    styrka: "50 mg/ml",
    recept: "",
    dosiMg: 2,
    dosIµG: "",
    obs: " ",
  },
  {
    drugId: "l14",
    catId: ["c6"],
    drugName: "Penthotal",
    styrka: "25 mg/ml",
    recept: "1 st Torrrampull i 20 ml Sterilt vatten",
    dosiMg: 5,
    dosIµG: "",
    obs: " ",
  },
  {
    drugId: "l15",
    catId: ["c6"],
    drugName: "Propofol",
    styrka: "10 mg/ml",
    recept: "",
    dosiMg: 2,
    dosiMg_2: 3,
    dosIµG: "",
    obs: " ",
  },
  {
    drugId: "l16",
    catId: ["c6"],
    drugName: "Alfentanil",
    styrka: "0.5 mg/ml",
    recept: "",
    dosiMg: "",
    dosIµG: 5,
    dosIµG_2: 10,
    dosIµG_3: 20,
    obs: " ",
  },
];
